#Kiểm tra phần tử thành viên với toán tử in và not in
a = [100, 200, 300, 500, 600, 900, 400, 800]
print(100 in a)
print(300 not in a)
#Tìm một phần tử trong danh sách ta dùng index()
print(a.index(100))
#Sắp xếp danh sách ta dùng sort()
a.sort()
print(a)
#Đảo ngược danh sách ta dùng reverse()
a.reverse()
print(a)
#Tìm giá trị lớn nhất và nhỏ nhất trong danh sách ta dùng max(), min()
print(max(a))
print(min(a))
#Tính tổng các phần tử có trong danh sách ta dùng sum()
print(sum(a))
#Đếm số lần phần tử xuất hiện ta dùng count()
count = a.count(100)
print(count)
#Nối các danh sách dùng dấu"+" hoặc extend()
b=[10,20,30]
c = a+b
a.extend(b)
print(c)
print(a)
#Sao chép danh sách ta dùng copy()
d=a.copy()
print(d)